server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.144.226.17:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: toor
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: wozhizaiyi
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://192.144.226.17:6868/eureka/
  instance:
    prefer-ip-address: true
